name: C/C++ CI

on: [push]

jobs:
  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: run cmake
      run: cmake .

    - name: run make
      run: make

    - name: run labo03
      run: ./bin/labo_03_basset_nils_lange_yanik_gallay_david <<< '\n'